Simulasi Gagal SonarWay

diff --git a/.github/workflows/continuous-inspection.yml b/.github/workflows/continuous-inspection.yml
--- a/.github/workflows/continuous-inspection.yml
+++ b/.github/workflows/continuous-inspection.yml
@@ -4,10 +4,12 @@ on:
   push:
     branches:
       - main
+      - contoh-gagal-rakan
   pull_request:
     types: [opened, synchronize, reopened]
     branches:
       - main
+      - contoh-gagal-rakan
 
 permissions:
   contents: read
@@ -22,6 +24,12 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - name: Check Quality Gate Threshold (Simulated)
+        if: github.ref == 'refs/heads/contoh-gagal-rakan'
+        run: |
+          echo "Error: Quality Gate failed because Reliability Rating is D (Threshold is B)."
+          exit 1
 
       - name: Set up JDK 22
         uses: actions/setup-java@v4
